//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ui.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUpdates
    {
        public int VersionId { get; set; }
        public string Version { get; set; }
        public string PatchNotes { get; set; }
        public string EXE_Name { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public Nullable<int> Channel { get; set; }
    }
}
