//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ui.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasswordArchive
    {
        public int PasswordId { get; set; }
        public int AccountId { get; set; }
        public string Password { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> DeactivationDate { get; set; }
    }
}
