//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ui.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMethods
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string MethodName { get; set; }
        public string PaypalUserId { get; set; }
        public Nullable<long> CrCardNumber { get; set; }
        public Nullable<int> CrCardChecksum { get; set; }
        public Nullable<System.DateTime> CrCardExpDate { get; set; }
        public Nullable<int> SoUeberweisungId { get; set; }
    }
}
